---
- name: install uStreamer
  import_tasks: ustreamer.yml
  tags:
    - ustreamer

- name: install nginx
  import_tasks: nginx.yml

- name: create the `lib` directory if it does not exist
  file:
    path: "{{ tinypilot_privileged_dir }}/lib"
    state: directory

- name: copy `lib` scripts
  copy:
    src: "{{ item }}"
    dest: "{{ tinypilot_privileged_dir }}/lib/{{ item | basename }}"
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - lib/*

- name: install HID USB gadget
  import_tasks: install_usb_gadget.yml

- name: install TinyPilot Debian package
  apt:
    deb: "{{ tinypilot_debian_package_path }}"

- name: create TinyPilot app settings
  template:
    src: tinypilot-app-settings.cfg.j2
    dest: "{{ tinypilot_app_settings_file }}"
    owner: "{{ tinypilot_user }}"
    group: "{{ tinypilot_group }}"
  notify:
    - restart TinyPilot service
  tags:
    - app-settings

- name: install TinyPilot as a service
  template:
    src: tinypilot.systemd.j2
    dest: /lib/systemd/system/tinypilot.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload TinyPilot systemd config
    - restart TinyPilot service

- name: enable systemd TinyPilot service file
  systemd:
    name: tinypilot
    enabled: yes
