---
- name: install uStreamer
  import_tasks: ustreamer.yml
  tags:
    - ustreamer

- name: install TinyPilot Debian package
  apt:
    deb: "{{ tinypilot_debian_package_path }}"

- name: create TinyPilot app settings
  template:
    src: tinypilot-app-settings.cfg.j2
    dest: "{{ tinypilot_app_settings_file }}"
    owner: "{{ tinypilot_user }}"
    group: "{{ tinypilot_group }}"
  notify:
    - restart TinyPilot service
  tags:
    - app-settings

- name: install TinyPilot as a service
  template:
    src: tinypilot.systemd.j2
    dest: /lib/systemd/system/tinypilot.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload TinyPilot systemd config
    - restart TinyPilot service

- name: enable systemd TinyPilot service file
  systemd:
    name: tinypilot
    enabled: yes

- name: install nginx
  import_tasks: nginx.yml
